version: "3.8"
services:
  db:
    build: ./db/

  futaba:
    build:
      context: ../
      target: "app"
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
      dockerfile: ./docker/app/Dockerfile
    user: $UID:$GID
    depends_on:
      - db
